installer: Correct SOS flashing for Pi Zero and Pi Zero W
FooDeas/raspberrypi-ua-netinst pull request #85
Opened 2017-07-15 22:01 UTC by dinosore

On the Pi Zero and Zero W, 0 turns the led on and 1 turns it off.  led0 is the activity led on the Zeros.

This is the opposite way round to other models.
I have tested the code on a Pi Zero W and a Model B;

2017-07-27 22:00 UTC, FooDeas requested changes

2017-07-27 22:00 UTC, FooDeas commented on scripts/opt/raspberrypi-ua-netinst/install.sh
> +	led_off=
Please move them into the `led_sos()` function and declare them `local`.

2017-07-27 22:00 UTC, FooDeas commented on scripts/opt/raspberrypi-ua-netinst/install.sh
> +		if [ -n "$led1" ]; then (echo $led_on > "${led1}"/brightness) &> /dev/null; fi
`${led_on}` and `${led_off}`

2017-07-27 22:00 UTC, FooDeas commented on scripts/opt/raspberrypi-ua-netinst/install.sh
> +
Move into the sos function, too.

2017-07-28 10:29 UTC, dinosore commented
done

2017-07-28 10:32 UTC, FooDeas approved these changes

2017-07-28 10:33 UTC, merged

2017-07-28 10:38 UTC, FooDeas commented
Thanks a lot!